Added possibility to give labels to aircraft
dronetag/drone-scanner pull request #2
Opened 2022-08-15 10:00 UTC by matejglejtek

2022-08-18 09:01 UTC, marianhlavac commented
```
❯ flutter run
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `device_info_plus` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this
command.
```

Budeme muset zmigrovat projekt

2022-08-18 12:55 UTC, marianhlavac requested changes
<img src="https://user-images.githubusercontent.com/3010503/185399752-c73f2a1d-9ab2-4e37-91a4-86bdcf032c0c.jpeg" width="240" />

Awesome feature 😄 Good job. I have just a few remarks.

2022-08-18 12:55 UTC, marianhlavac commented on lib/bloc/aircraft/aircraft_cubit.dart
> +  // labels are stored locally on device,
It's better to describe what the method does, so something more like "Retrieves the labels stored persistently locally on the device". Same goes for the `addAircraftLabel` method, better to write "Stores the label persistently locally on the device"

2022-08-18 12:55 UTC, marianhlavac commented on lib/bloc/map/map_cubit.dart
> +                  }
```suggestion
                  final haslocation = !(e.isEmpty ||
                      e.last.locationMessage == null ||
                      e.last.locationMessage?.latitude == null ||
                      e.last.locationMessage?.longitude == null);
```

A bit unnecessary variable modification and if condition here

2022-08-18 12:55 UTC, marianhlavac commented on lib/widgets/sliders/aircraft/aircraft_card_title.dart
> +  }
```suggestion
      return Text.rich(
        TextSpan(
          style: const TextStyle(
            fontWeight: FontWeight.bold,
          ),
          children: [
          if (givenLabel != null)
            WidgetSpan(
                alignment: PlaceholderAlignment.middle,
                child: Icon(Icons.label_outline,
                    size: Sizes.textIconSize, color: Colors.black),
              )
          else if (uasId.startsWith('1596') == true)
              WidgetSpan(
                alignment: PlaceholderAlignment.middle,
                child: Image.asset('assets/images/dronetag.png',
                    height: 16,
                    width: 24,
                    alignment: Alignment.topRight,
                    color: Colors.black),
              ),
            TextSpan(
              text: givenLabel ?? uasId,
            ),
          ],
        ),
      );
```

Some parts of the code here needs not to be duplicated

2022-08-19 09:51 UTC, matejglejtek commented on lib/widgets/sliders/aircraft/detail/aircraft_label_text.dart
> +                    'Would you really like to delete aircraft label?',
changed according to suggestion

2022-08-19 09:56 UTC, matejglejtek commented on lib/widgets/sliders/aircraft/aircraft_card_title.dart
> +  }
duplicates removed

2022-08-19 09:58 UTC, matejglejtek commented on lib/bloc/map/map_cubit.dart
> +                  }
suggestion adopted

2022-08-24 14:55 UTC, marianhlavac approved these changes
Looks good, please resolve the conflicts that has appeared and it's ready to merge.

2022-08-24 15:09 UTC, merged