Add help page
dronetag/drone-scanner pull request #24
Opened 2022-11-09 09:25 UTC by matejglejtek

2022-11-11 16:24 UTC, marianhlavac requested changes
It looks great, only two things to polish:

* vertical space at the end of Help screen
* correct question to show when tapping the help link in prefs

2022-11-11 16:24 UTC, marianhlavac commented on lib/widgets/help/help_page.dart
> +  static const iphoneWifiQuestionIndex = 3;
We have to choose different strategy to reference the wi-fi help question, because using index will result (as it happened now) in displaying different question after someone re-sorts it on CMS.

In the current JSON, the ID is there, but it's kind of hard to use, so I suggest changing the URL to:

```
https://cms.dronetag.cz/items/drone_scanner_help_section?fields=*,displayed_questions.question.translations.*,displayed_questions.question.id
```

There is `displayed_questions.question.id` added and this URL should include the ID of the question in the resulting JSON.

None of the current questions are ideal for the wi-fi help link, but personally I think the closes one is ID 9  ("How can I find out what my phone is capable of?"), so let's use this one.

2022-11-11 20:10 UTC, matejglejtek commented on lib/widgets/help/help_page.dart
> +class HelpPage extends StatelessWidget {
I decided to use safe area for every page, also preferences page missed vertical space at the bottom.

2022-11-11 20:31 UTC, matejglejtek commented on lib/widgets/help/help_page.dart
> +  static const iphoneWifiQuestionIndex = 3;
Id is now read from JSON, not given by question order. I used id 9 as the question that opens using the link from preferences. I think we will need to adjust an answer to include specific information about iOS, something like 'Apple does not provide a tools for developers that would enable them to implement scanning using Wi-Fi.'

2022-11-13 21:34 UTC, marianhlavac commented on lib/widgets/help/help_page.dart
> +  static const iphoneWifiQuestionIndex = 3;
Agreed. Thanks for this edit though.

2022-11-13 21:50 UTC, marianhlavac commented on lib/widgets/help/help_page.dart
> +class HelpPage extends StatelessWidget {
Great thought, safe area is better option, only now on some devices this caused visible padding. I think that the safe area must be applied on the scrollable element, in case of ListView, I think the safe area somehow builtin, check out the documentation.

![IMG_0490](https://user-images.githubusercontent.com/3010503/201546225-07f9b6eb-96d3-4f26-83ef-e646669db28a.PNG)

2022-11-14 11:41 UTC, matejglejtek commented on lib/widgets/help/help_page.dart
> +class HelpPage extends StatelessWidget {
Yes it is true that list view has [builtin safe area](https://stackoverflow.com/a/52106410), but it is already disabled, because i used padding: EdgeInsets.zero.

From my research, the padding you mention appears on iPhone without home button (X and newer), probably so you do not close the app accidentally because the area catches gestures. You can see this padding in other apps(native/3rd party), but is usually incorporated in navigation bar or status bar, so it is not catching the eye so much.

Here are some examples - from top: litacka, photos, mail, safari, twitter
![IMG_3668](https://user-images.githubusercontent.com/15686037/201650753-1fa99355-dd4b-4251-9140-a61ca664afb9.jpeg)

![IMG_3669](https://user-images.githubusercontent.com/15686037/201650756-84c90101-0ab3-4ad3-a342-851122a53a05.jpeg)

![IMG_3670](https://user-images.githubusercontent.com/15686037/201650760-53a0d257-ff8b-47f4-a6a7-cc176b5a495c.jpeg)

![IMG_3671](https://user-images.githubusercontent.com/15686037/201650762-b4b85247-63d2-461b-b5a7-90ba3d5eab0a.jpeg)

![IMG_3665](https://user-images.githubusercontent.com/15686037/201650751-40e7a69f-d648-4d9c-992f-427a3894cd27.jpeg)

2022-11-14 18:16 UTC, marianhlavac commented on lib/widgets/help/help_page.dart
> +class HelpPage extends StatelessWidget {
> but it is already disabled, because i used padding: EdgeInsets.zero.

EdgeInsets.zero disables the builtin safe area, while we want the exact opposite - to use safearea builtin from the ListView.

2022-11-14 18:17 UTC, marianhlavac requested changes
Please try using builtin padding of ListView to achieve the same spacing as when SafeArea is used as the parent. After that the PR is ready to be merged.

2022-11-15 12:50 UTC, marianhlavac approved these changes
Awesome.

2022-11-15 12:51 UTC, merged