UI polishing
dronetag/drone-scanner pull request #3
Opened 2022-08-16 13:25 UTC by matejglejtek

Completion of UI according to figma design, adjustments to aircraft detail view

2022-08-18 13:05 UTC, marianhlavac requested changes
The project is missing the `assets/config/uasid_prefix.json` file, cannot make the build without the file, app crashes on start. Pls include in the project if it's not sensitive.

2022-08-18 13:07 UTC, marianhlavac commented on lib/utils/utils.dart
> +  if (manufacturer == 'DJI') path = 'assets/images/dji_logo.png';
I'd later convert these logos into an icon pack (same as the DroneScannerIcons font) and use the vector variants. Just an improvement, no need to change it in this PR.

2022-08-25 19:41 UTC, matejglejtek commented
I swapped icons in list card for ones from design, changed spacing in card and slider headers, adjusted some colors, made flags circular etc. I will test it on different screensizes asap.

2022-08-26 08:03 UTC, marianhlavac commented
![Screenshot_20220826-095626](https://user-images.githubusercontent.com/3010503/186852609-35225da7-1c9a-4da2-a79a-4a42421c6da2.jpg)

There is overflow on the details and the objects on the top of the detail panel are misaligned. The icons inside the buttons are also misaligned (too large and not centered)

2022-08-26 08:25 UTC, marianhlavac requested changes
The UI has been improved by this PR greatly, a lot of work went into this, however there are still a few important details missing, overflows are still present and some elements seem misaligned. I'd advise one final check against the Figma design.

Also a few conflicts has appeared, let's resolve then before we can merge.

2022-08-28 10:52 UTC, matejglejtek commented
Overflows were fixed, as well as position of side toolbar.

2022-08-29 09:11 UTC, marianhlavac requested changes
There are still issues to be fixed, I've shared the list of issues with you.

2022-08-30 19:00 UTC, matejglejtek commented
I disabled landscape mode, changed layout of about dialog and showcase items. I corrected grammar is showcase texts. There is also new wifi icon without watermark.
In opendroneid library I fixed a problem that probably caused problem with starting scans.

2022-09-02 11:47 UTC, matejglejtek commented
I changed showcase items so they have the same styling, size and are centered to the middle of the screen.
I fixed colors of back buttons in license page and searching for places page.

2022-09-04 19:52 UTC, marianhlavac approved these changes
Alright, looks solid now, good job! Any further UI issues we'll cover in another issues.

2022-09-04 19:53 UTC, merged