Fix: unknown values in messages from aircraft
dronetag/drone-scanner pull request #33
Opened 2022-11-28 11:30 UTC by matejglejtek

Handle cases with unknown values for all possible fields of remote id messages.

2022-11-29 14:25 UTC, marianhlavac requested changes
I have suggested some changes, please take a look at them.

2022-11-29 14:25 UTC, marianhlavac commented on lib/widgets/sliders/aircraft/aircraft_card.dart
> +            : 'Unknown Status';
![Screenshot_20221129_151012](https://user-images.githubusercontent.com/3010503/204551255-a7d10cb2-56c2-45fc-a1e0-603a9541b895.jpg)

The text should have textAlign: center to be centered when it wraps to two lines. It should also be centered horizontally with the icon in the parent container. I've drafted what is the desired layout of these elements and what should be avoided.

![Untitled-2022-11-29-1514 excalidraw-2](https://user-images.githubusercontent.com/3010503/204553392-5bc43488-eb5e-4761-b0cd-11d8557830f0.png)

2022-11-29 14:25 UTC, marianhlavac commented on lib/widgets/sliders/aircraft/aircraft_card.dart
> +    if (messagePack.locationMessage == null) return 'Unknown Status';
Those two words seems to be visually cramped. What if we keep just "Unknown"?

2022-11-29 14:25 UTC, marianhlavac commented on lib/widgets/sliders/aircraft/aircraft_card.dart
> +                      Icons.error_outline,
The error icon feels too angry. The `Icons.help_outline` icon feels better, even though the name of the icon is not matching the context.

2022-11-30 10:50 UTC, matejglejtek commented
I changed the icon when status is unknown, changed text and fixed alignment.

2022-11-30 12:23 UTC, marianhlavac approved these changes

2022-11-30 12:23 UTC, merged