Feature: permissions handling
dronetag/drone-scanner pull request #36
Opened 2023-01-09 11:33 UTC by matejglejtek

Refresh permissions statuses after user returns to app.
Do not allow starting scans without location permission on Android. Notify user using snackbars.

2023-01-18 12:24 UTC, matejglejtek commented
Depends on [flutter-odid PR](https://github.com/dronetag/flutter-opendroneid/pull/11)

2023-01-19 12:01 UTC, albertmoravec requested changes
Minor code style fix, jinak gut. V mobilce si s tim budem muset vic pohrat, protoze se bude zapinat OpenDroneID i Harald najednou, coz bude mozna pain.

2023-01-25 16:02 UTC, marianhlavac commented
Updatnuto aby to sedelo s posledni verzi flutter_opendroneid

2023-01-25 16:06 UTC, marianhlavac approved these changes

2023-01-25 17:07 UTC, merged