Fix: CSV exports
dronetag/drone-scanner pull request #41
Opened 2023-04-19 10:09 UTC by matejglejtek

Fix exported file format, use 1 common header on 1st row. Fix timestamp.

2023-04-24 14:22 UTC, marianhlavac requested changes
![Screenshot 2023-04-24 at 16 21 24](https://user-images.githubusercontent.com/3010503/234025279-bb722504-c3bb-45e1-9dfb-5b83d4c40824.png)

To se uplne nepovedlo. Exportoval jsem si let na iOS a otevrel soubory ktere to vygenerovalo.

Prosim proste o dukladnou kontrolu, tohle preci neni ready na merge.

2023-04-24 16:10 UTC, matejglejtek commented
> ![Screenshot 2023-04-24 at 16 21 24](https://user-images.githubusercontent.com/3010503/234025279-bb722504-c3bb-45e1-9dfb-5b83d4c40824.png)
> 
> To se uplne nepovedlo. Exportoval jsem si let na iOS a otevrel soubory ktere to vygenerovalo.
> 
> Prosim priste o dukladnou kontrolu, tohle preci neni ready na merge.

"Your Remote ID Data" je text ktory sa defaultne nastavi ako telo spravy ked vyberes v share dialogu poslat ako email/spravu.  Vyzera to ale ze sa ten text ulozi to .txt filu ked das na iOS save to files, to som si nevsimol. 
Ale aj tak by sa ti mali data vyexportovat, nemas vedla toho csv file? mne to teraz ulozi ten txt ale aj .csv vedla toho

2023-04-24 16:29 UTC, matejglejtek commented
Odstranil som ten parameter 'subject' a 'text' z volania _shareXFiles_ na iOS, pouziva sa len na Androide. Pri save to files sa mi ulozi subor drone_scanner_export_uasid.csv

2023-05-01 19:45 UTC, marianhlavac requested changes
Funkce stale nefunguje, nyni vraci CSV o nulove velikosti se kterym nelze nic delat.


https://user-images.githubusercontent.com/3010503/235518581-8884f825-53c0-4082-b007-2a06ab578e05.MP4

2023-05-02 13:43 UTC, matejglejtek commented
jedine co mi napada je permission, zeptalo se te to na storage permission? Ak si mal na telefone nejaku starsiu verziu appky a neodinstaloval si ju tak sa mohlo stat ze storage permission bol v stave denied a ten dialog nevyskoci pokial uz raz pemission odmietnes.

2023-05-15 10:57 UTC, marianhlavac requested changes
Aplikaci jsem kompletne odinstaloval a znovu nainstaloval. Je vsak nutne mit na pameti ze prakticky nikdo po updatu appku reinstalovat nebude, takze bude ve stejne situaci.

Ani pres reinstall funkcionalita stale nefunguje. Zero kB soubor. Po odkliknuti se zobrazi snackbar "Exporting was not successful".

2023-05-26 14:14 UTC, marianhlavac commented
Vyzkousejme co to bude delat az to buildneme do Testflightu, vypada to ze mi to nevali jen lokalne.

2023-05-26 14:15 UTC, merged