Project Documentation
dronetag/drone-scanner pull request #5
Opened 2022-08-18 11:23 UTC by matejglejtek

New markdown files with description of application features, standards followed, project architecture, dependencies and build steps.
Instructions how to contribute.

2022-08-18 13:38 UTC, marianhlavac requested changes
**The docs looks good, I've added some requests.**

---
![Screenshot 2022-08-18 at 15 12 45](https://user-images.githubusercontent.com/3010503/185403574-aaf23128-eddd-4a6f-9b19-4e4d0dd6cc36.png)

There seems to be few accidental unrelated commits in this PR, can we remove then from this PR and isolate them to a separate PR?

- [ ] Separate the unrelated commits to a different PR

2022-08-18 13:38 UTC, marianhlavac commented on README.md
> +* [Dronetag Devs](https://devs.dronetag.cz) – more links for all Dronetag devs
Hmmmm 🤔 😄 
I would suggest linking them to our [Developers section on the help site](https://help.dronetag.cz/developers) and creating a dedicated section for this. What do you think?

2022-08-18 13:38 UTC, marianhlavac commented on README.md
> +|![s](/assets/screenshots/map_page.jpg)    | ![s](/assets/screenshots/detail.jpg) |
Cool GIFs! I'd just make them smaller to shorten the README a bit, it's kinda long because of the screenshots. We can make the images a links to full size so people can click on them and see in full size.

2022-08-18 13:38 UTC, marianhlavac commented on docs/architecture.md
> +* 📂 `widgets` – Folder with source code of Flutter widgets, organized in features.
Not sure if this was intended, but the `widgets` folder is under `lib` so I feel like this doesn't fit here, plus it's mentioned on L17, so maybe remove this one in favor of the next one?

2022-08-18 13:38 UTC, marianhlavac commented on docs/build.md
> +
I'm not sure if we're able to keep this list in sync with the real dependencies in the project, so I'd write here something like:

> Here is a list of the significant dependencies and their role in this project.

And maybe we can remove some smaller or insignificant dependencies, such as permission_handler, or sliding_up_panel.

2022-08-18 13:38 UTC, marianhlavac commented on README.md
> -The files which contain Google Maps API are added to .gitignore, so your key will not be accidentally commited. If you wish to commit changes in these files, use 'git add -f file'.
This shouldn't be removed, it's non-standard and also vital for spinning up the project and should stay in README, even if it's been moved to different doc.

2022-08-24 14:34 UTC, matejglejtek commented on docs/architecture.md
> +* 📂 `widgets` – Folder with source code of Flutter widgets, organized in features.
line removed

2022-08-24 14:37 UTC, matejglejtek commented on docs/build.md
> +
dependencies list edited

2022-08-24 14:39 UTC, matejglejtek commented on README.md
> -The files which contain Google Maps API are added to .gitignore, so your key will not be accidentally commited. If you wish to commit changes in these files, use 'git add -f file'.
I moved the paragraph back to readme

2022-08-24 14:47 UTC, matejglejtek commented on README.md
> +|![s](/assets/screenshots/map_page.jpg)    | ![s](/assets/screenshots/detail.jpg) |
I made images smaller, they work as links.

2022-08-24 14:55 UTC, matejglejtek commented on README.md
> +* [Dronetag Devs](https://devs.dronetag.cz) – more links for all Dronetag devs
I created separate file for resources with link to our help site.

2022-08-24 15:03 UTC, matejglejtek commented
> There seems to be few accidental unrelated commits in this PR, can we remove then from this PR and isolate them to a separate PR?

Yes the commits were accidentaly pushed here, they belong to the DT-1969. Not sure how to remove them correctly, I will need some advice on this.

2022-08-26 08:27 UTC, marianhlavac commented on README.md
> +* [Dronetag Devs](https://devs.dronetag.cz) – more links for all Dronetag devs
Sorry for being vague, I thought that it was immediately obvious – the link devs.dronetag.cz does not exist and never did.

2022-08-26 08:28 UTC, marianhlavac commented
> Not sure how to remove them correctly, I will need some advice on this.

No prob, let's look at it together in the office and we'll clean them up.

2022-08-26 08:33 UTC, marianhlavac requested changes
There is still some unresolved stuff + we need to clean up the unrelated commits.

2022-08-26 12:53 UTC, marianhlavac commented on CONTRIBUTING.md
> +- we use [stable mainline branching model](https://www.bitsnbites.eu/a-stable-mainline-branching-model-for-git/)
```suggestion
- we use [stable mainline branching model](https://www.bitsnbites.eu/a-stable-mainline-branching-model-for-git/) with squashing instead of merge commits
```

2022-08-26 12:54 UTC, marianhlavac approved these changes

2022-08-26 12:55 UTC, merged