Feat: bump and remove packages
dronetag/drone-scanner pull request #67
Opened 2023-12-20 13:24 UTC by matejglejtek

In this PR i originally wanted to solve [DT-2777](https://dronetag.atlassian.net/browse/DT-2777) by updating `osm_flutter_plugin` and `permission_handler `packages to sync with other repos and to be able to bump flutter-odid.

After dealing with few conflicts and finding out newest `osm_flutter_plugin` is still not compatible, I decided to remove `osm_flutter_plugin` package and use own client to Nominatim API we have in the app. 

I also removed unused `flogs` and bumped `flutter-opendroneid` to latest.

2023-12-20 13:28 UTC, matejglejtek commented on lib/bloc/standards_cubit.dart
> -    FLog.info(text: 'maxAdvDataLen $maxAdvDataLen');
I remember we wanted to send this information to our servers to keep track of capabilities of smartphones. That is probably the reason flogs were used here but I think we can choose better logger when it will be required.

2023-12-31 16:58 UTC, marianhlavac requested changes
Apart from the crash when tapping the erase button, this is a welcomed addition!

2023-12-31 16:58 UTC, marianhlavac commented on lib/bloc/standards_cubit.dart
> -    FLog.info(text: 'maxAdvDataLen $maxAdvDataLen');
Seems we never collected that data, let's keep it in the console output now and we'll figure out the data collection later, I'd choose a different tools to do this, and there are more stuff related to this, such as allowing users to opt-out from the data collection or disclosing the collection in the app stores.

2023-12-31 16:58 UTC, marianhlavac commented on lib/widgets/toolbars/components/location_search.dart
> +    _disposeOverlayEntry(context);
This gets called when tapping the "trash" button on the search bar and crashes for me:

```
[sentry.platformError] [error] Uncaught Platform Error
[sentry.platformError] _AssertionError ('package:flutter/src/widgets/overlay.dart': Failed assertion: line 168 pos 12: '_overlay != null': is not true.)
[sentry.platformError] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
                       #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
                       #2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:168:12)
                       #3      _LocationSearchState._disposeOverlayEntry (package:drone_scanner/widgets/toolbars/components/location_search.dart:246:23)
                       #4      _LocationSearchState._refreshOverlay (package:drone_scanner/widgets/toolbars/components/location_search.dart:225:5)
                       #5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
                       #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
                       #7      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
                       #8      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
                       #9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
                       #10     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
                       #11     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

2024-01-01 21:46 UTC, albertmoravec approved these changes
Really nice, I just have one possible UX improvement.

2024-01-01 21:46 UTC, albertmoravec commented on lib/widgets/toolbars/components/location_search.dart
> +            _disposeOverlayEntry(context);
When results are loading and user submits, maybe it would be more intuitive to continue loading instead?

2024-01-02 13:06 UTC, matejglejtek commented
Rebased, resolved the crash when using trash icon, implemented @albertmoravec's suggestion.

2024-01-02 15:34 UTC, marianhlavac approved these changes
Perfect.

2024-01-02 15:34 UTC, merged