feat: show data authenticity status
dronetag/drone-scanner pull request #78
Opened 2024-05-09 12:27 UTC by matejglejtek

Use flutter-opendroneid with a spoofer detection.

Show data status on aircraft detail header.

Spoofer caused issue with flags. Flags are fetched for country code from operator id. Spoofer had some random country code which caused an exception when using `NetworkImage('https://flagcdn.com/h20/${countryCode.toLowerCase()}.png')` The exception could not be catched so I reimplemented flag fetching, moved accessing `flagcdn.com` endpoint to separate client. 

I also refactored `AircraftCubit`, I moved labels, manufacturer info and flags to new `AircraftMetadataCubit`.

2024-05-13 11:15 UTC, matejglejtek commented
I moved the `MessageContainerAuthenticator` from flutter-opendroneid here. 
Containers are authenticated in `addPack` method in `AircraftCubit`. Result is stored in `AircraftState` in a map with mac address as a key.

2024-05-16 15:34 UTC, albertmoravec approved these changes
Not sure how cache invalidation is handled, but the code looks good. Probably consult the "Untrusted" label situation with @marianhlavac before it gets released.

2024-05-17 09:23 UTC, marianhlavac requested changes
This is awesome first step to bring the

Agreed with @albertmoravec, not only because this is still kinda experimental, let's display only "Suspicious" or "Counterfeit". At least until we figure out how to achieve our own devices to show up as trusted. Lastly, we'll bring UI design for this, so it looks better.

Good job!

2024-05-17 09:23 UTC, marianhlavac commented on lib/utils/message_container_authenticator.dart
> +    // spoofed if all values are set as expected
Instead of "as expected", please mention a reference to the ESP spoofer:

```
// Mark as spoofed if all values are exactly the same as the values used by RemoteIDSpoofer
```

Applies to multiple places in this code.

2024-05-21 08:37 UTC, marianhlavac commented
🔴 Currently blocked on not being able to build on Flutter 3.22 – let me know if it's possible to update Drone Scanner for 3.22, or I should downgrade to review this. Thx!

2024-05-21 15:54 UTC, marianhlavac approved these changes
Downgraded Flutter to test this PR. Looks & works great, thx! 💯

2024-05-21 16:29 UTC, merged