Set up sentry for reporting errors
dronetag/drone-scanner pull request #8
Opened 2022-09-08 13:31 UTC by matejglejtek

2022-09-09 07:05 UTC, marianhlavac commented
Rebased nad posledni master

2022-09-09 07:58 UTC, marianhlavac requested changes
The environment variables didn't work for me, otherwise tested and works.

2022-09-09 07:58 UTC, marianhlavac commented on lib/main.dart
> +        throw Exception('There is no Sentry DSN specified!');
I think we shouldn't crash the app with an exception when Sentry DSN is missing, it makes development complicated for developers without access to the DSN string, wanting to try the app in the release mode.

2022-09-09 07:58 UTC, marianhlavac commented on lib/main.dart
> +          options.debug = kDebugMode;
Sentry would never run with debug mode enabled, if we prevent calling .init() when kDebugMode==false.

2022-09-09 07:58 UTC, marianhlavac commented on lib/main.dart
> +final sentryDsn = String.fromEnvironment(
For some reason it's not working for me.

Running the app with `❯ flutter run --release --dart-define=SENTRY_DSN=...` doesn't do the trick. Either this should support standard behavior and setting of environment variables, or the setup should be described in README.md or docs/..., but the former is preferred, of course.

2022-09-22 10:35 UTC, matejglejtek commented
rebased nad posledni master

2022-09-22 10:39 UTC, matejglejtek commented on lib/main.dart
> +final sentryDsn = String.fromEnvironment(
changed type of sentryDsn from 'final' to 'const', now it works.

2022-09-22 10:40 UTC, matejglejtek commented on lib/main.dart
> +        throw Exception('There is no Sentry DSN specified!');
fixed, app now continues running

2022-09-22 11:04 UTC, marianhlavac approved these changes
Thanks for fixing the issue with env vars, looks good.

2022-09-22 11:04 UTC, merged