feat: positive spoofer detectors
dronetag/drone-scanner pull request #82
Opened 2024-06-04 14:43 UTC by matejglejtek

Add 2 new detectors: `LocationTimestampSpooferDetector` and `LocationSpooferDetector`. Show all data authenticity statuses in app UI.

`LocationSpooferDetector` compares phone location with the drone location and returns spoofed probability based on distance. 

`LocationTimestampSpooferDetector` compares timestamp from location message with system time.

2024-06-06 11:35 UTC, marianhlavac requested changes
Fantastic, it's even better now, but I'd still consider it as a great start rather than polished feature – but that's something we acknowledge in the team. We'll be fine-tuning the score system further – sometimes it's inconsistent. For RID device that was obtaining the fix, there was a period when it was "Untrusted" and short period when it was "Verified".

I'm proposing a slight change of wording, Verified -> Trusted. I'd reserve the word "Verified" for cases where we actually really verify the validity against some authority or valid signature.

We'll have a lot of work in front of us with this feature, but it's obvious this will be very useful feature when we fine-tune and polish it. I'd target for Drone Scanner v2 to have this feature in final & polished state.

2024-06-06 13:04 UTC, matejglejtek commented on lib/utils/message_container_authenticator.dart
> +    // Score bellow 1/4 is considered verified.
I added new `trusted` status, that is now used instead of verified. I kept verified for actually verified against some authority.

2024-06-06 13:05 UTC, matejglejtek commented
I implemented change of wording Verified -> Trusted. I also asked our aspiring QA engineer Mr. Tetauer to try the feature.

2024-06-08 18:36 UTC, marianhlavac approved these changes

2024-06-08 19:08 UTC, merged