feat: add location timestamp to export
dronetag/drone-scanner pull request #91
Opened 2024-10-03 13:48 UTC by matejglejtek

Add location timestamp to CSV export. I kept it in original format: elapsed duration from start of last full hour. We could add last full hour to create complete timestamp but result may be wrong if eg. duration is 59 m 59s and packet is received in the next hour.

2024-10-07 10:55 UTC, marianhlavac requested changes
Could you please take a closer look at the Duration textual representation function? It doesn't seem to meet the expected level of quality.

2024-10-07 10:55 UTC, marianhlavac commented on lib/utils/csvlogger.dart
> +  }
This is a really weird code.

1. Why do you calculate everything from the milliseconds manually, when there are members, such as `inHours` and `inMinutes` available to serve this exact purpose?
2. Why don't we go ahead and don't use the `toString()` method on the _Duration_ instance? It's not exactly the case, but isn't it better to adjust the string (remove last few digits after last dot) than re-building it completely?
3. Duration can never be in hours? The string always starts with `00:`

2024-10-07 12:46 UTC, matejglejtek commented on lib/utils/csvlogger.dart
> +  }
I reimplemented it to use toString

2024-10-08 06:29 UTC, marianhlavac approved these changes

2024-10-08 08:11 UTC, merged

2024-10-27 13:31 UTC, shoradrustum commented on lib/utils/csvlogger.dart
Received Timestamp